driver:
  name: docker
  privileged: true
  remove_images: false

provisioner:
  name: chef_solo

platforms:
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[porta_user::default]
      - recipe[porta_user-test::create]
    attributes:
