name 'porta_user'
maintainer 'Jonathan Porta'
maintainer_email 'jonathan@jonathanPorta.com'
license 'WTFPL'
description 'Library cookbook that provides porta_user'
long_description 'Library cookbook that provides porta_user'
version '0.0.1'

depends 'user'
depends 'sudo'
